CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL
);

INSERT INTO posts (title, body) VALUES
('Post 1', 'This is the body of post 1.'),
('Post 2', 'This is the body of post 2.'),
('Post 3', 'This is the body of post 3.'),
('Post 4', 'This is the body of post 4.'),
('Post 5', 'This is the body of post 5.'),
('Post 6', 'This is the body of post 6.'),
('Post 7', 'This is the body of post 7.'),
('Post 8', 'This is the body of post 8.'),
('Post 9', 'This is the body of post 9.'),
('Post 10', 'This is the body of post 10.'),
('Post 11', 'This is the body of post 11.'),
('Post 12', 'This is the body of post 12.'),
('Post 13', 'This is the body of post 13.'),
('Post 14', 'This is the body of post 14.'),
('Post 15', 'This is the body of post 15.'),
('Post 16', 'This is the body of post 16.'),
('Post 17', 'This is the body of post 17.'),
('Post 18', 'This is the body of post 18.'),
('Post 19', 'This is the body of post 19.'),
('Post 20', 'This is the body of post 20.'),
('Post 21', 'This is the body of post 21.'),
('Post 22', 'This is the body of post 22.'),
('Post 23', 'This is the body of post 23.'),
('Post 24', 'This is the body of post 24.'),
('Post 25', 'This is the body of post 25.'),
('Post 26', 'This is the body of post 26.'),
('Post 27', 'This is the body of post 27.'),
('Post 28', 'This is the body of post 28.'),
('Post 29', 'This is the body of post 29.'),
('Post 30', 'This is the body of post 30.'),
('Post 31', 'This is the body of post 31.'),
('Post 32', 'This is the body of post 32.'),
('Post 33', 'This is the body of post 33.'),
('Post 34', 'This is the body of post 34.'),
('Post 35', 'This is the body of post 35.'),
('Post 36', 'This is the body of post 36.'),
('Post 37', 'This is the body of post 37.'),
('Post 38', 'This is the body of post 38.'),
('Post 39', 'This is the body of post 39.'),
('Post 40', 'This is the body of post 40.'),
('Post 41', 'This is the body of post 41.'),
('Post 42', 'This is the body of post 42.'),
('Post 43', 'This is the body of post 43.'),
('Post 44', 'This is the body of post 44.'),
('Post 45', 'This is the body of post 45.'),
('Post 46', 'This is the body of post 46.'),
('Post 47', 'This is the body of post 47.'),
('Post 48', 'This is the body of post 48.'),
('Post 49', 'This is the body of post 49.'),
('Post 50', 'This is the body of post 50.');
